name: insurance_claims_analytics
version: '1.0.0'
config-version: 2

profile: insurance_claims_analytics

model-paths: ["models"]

models:
  insurance_claims_analytics:
    staging:
      +schema: STAGING
      +materialized: view
    marts:
      +schema: MARTS
      +materialized: table
