CREATE OR REPLACE DATABASE INSURANCE_ANALYTICS_DB;

CREATE OR REPLACE SCHEMA INSURANCE_ANALYTICS_DB.RAW;
CREATE OR REPLACE SCHEMA INSURANCE_ANALYTICS_DB.STAGING;
CREATE OR REPLACE SCHEMA INSURANCE_ANALYTICS_DB.MARTS;

CREATE OR REPLACE TABLE INSURANCE_ANALYTICS_DB.RAW.CLAIMS_RAW (
    claim_id STRING,
    policy_id STRING,
    customer_id STRING,
    claim_date DATE,
    claim_type STRING,
    claim_amount NUMBER,
    claim_note STRING,
    state STRING
);
